name: Generate Breakout Game from GitHub Contributions

on:
  schedule:
    - cron: '0 0 * * 0' # runs weekly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Breakout Game from GitHub Contribution Graph
        uses: cyprieng/github-breakout@v1.2.1
        with:
          github_username: AnirudhPhophalia
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_ghost_bricks: true
          paddle_color: '#00FFAA'
          ball_color: '#FF0000'
          bricks_colors: '#00FF00,#0000FF,#FF00FF'
